# Generated by Django 5.2.3 on 2025-06-26 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymposiumRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('registration_type', models.CharField(blank=True, max_length=32, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('team_name', models.CharField(blank=True, max_length=128, null=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('delegation_fee', models.PositiveIntegerField(default=1500)),
                ('event_fee_per_delegate', models.PositiveIntegerField(default=3500)),
                ('accommodation_fee', models.PositiveIntegerField(default=0)),
                ('total_fee', models.PositiveIntegerField(default=0)),
                ('chaperone_name', models.CharField(blank=True, max_length=128, null=True)),
                ('chaperone_cnic', models.CharField(blank=True, max_length=32, null=True)),
                ('chaperone_mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('chaperone_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('chaperone_relationship', models.CharField(blank=True, max_length=128, null=True)),
                ('chaperone_designation', models.CharField(blank=True, max_length=128, null=True)),
                ('chaperone_image_url', models.URLField(blank=True, null=True)),
                ('chaperone_accommodation', models.CharField(blank=True, max_length=10, null=True)),
                ('undertaking', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SymposiumDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('cnic', models.CharField(blank=True, max_length=32, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('education_level', models.CharField(blank=True, max_length=64, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('accommodation', models.CharField(blank=True, max_length=10, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='users.symposiumregistration')),
            ],
        ),
    ]
