# Generated by Django 5.2.3 on 2025-06-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposiumregistration',
            name='ca_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='symposiumregistration',
            name='ca_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
