# Generated by Django 5.2.3 on 2025-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_symposiumregistration_ca_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposiumregistration',
            name='registered_through_ca',
            field=models.BooleanField(default=False),
        ),
    ]
