# Generated by Django 5.2.3 on 2025-07-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_campusambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposiumregistration',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='symposiumregistration',
            name='payment_voucher',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/'),
        ),
        migrations.AddField(
            model_name='symposiumregistration',
            name='team_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
