# Generated by Django 5.2.3 on 2025-07-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_symposiumregistration_payment_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposiumdelegate',
            name='date_of_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symposiumdelegate',
            name='date_of_departure',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symposiumdelegate',
            name='number_of_nights',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
