# Generated by Django 5.2.3 on 2025-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_symposiumdelegate_date_of_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symposiumregistration',
            name='delegation_fee',
            field=models.PositiveIntegerField(default=3500),
        ),
        migrations.AlterField(
            model_name='symposiumregistration',
            name='event_fee_per_delegate',
            field=models.PositiveIntegerField(default=4000),
        ),
    ]
