# Generated by Django 5.2.3 on 2025-07-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_symposiumregistration_delegation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposiumregistration',
            name='event_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
