# Generated by Django 5.2.3 on 2025-07-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_symposiumregistration_event_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symposiumregistration',
            old_name='event_fee',
            new_name='event1_fee',
        ),
    ]
