# Generated by Django 5.2.3 on 2025-07-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_event_fee_symposiumregistration_event1_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symposiumregistration',
            name='payment_voucher',
            field=models.URLField(blank=True, null=True),
        ),
    ]
