# Generated by Django 5.2.7 on 2025-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_formstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstate',
            name='cognito_save_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
